# Site settings
title: Tom Kraft Design
email: tom@tomkraftdesign.com
description: > # this means to ignore newlines until "baseurl:"
  Tom Kraft Design creates and maintains websites using open source platforms. Specifically the content management systems WordPress and Drupal.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://tomkraftdesign.com/" # the base hostname & protocol for your site



# Build settings
markdown: kramdown
